// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mjm.LocalDocs.Infrastructure.Persistence;

#nullable disable

namespace Mjm.LocalDocs.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocalDocsDbContext))]
    [Migration("20260215174229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.ApiTokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36);

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset?>("ExpiresAt");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastUsedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("TokenPrefix")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ApiTokens", (string)null);
                });

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.DocumentChunkEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<int>("ChunkIndex");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<string>("FileName")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "ChunkIndex");

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36);

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64);

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("ExtractedText")
                        .IsRequired();

                    b.Property<byte[]>("FileContent");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<long>("FileSizeBytes");

                    b.Property<string>("FileStorageLocation")
                        .HasMaxLength(1000);

                    b.Property<string>("MetadataJson");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<DateTimeOffset?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "FileName");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36);

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTimeOffset?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.DocumentChunkEntity", b =>
                {
                    b.HasOne("Mjm.LocalDocs.Infrastructure.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.HasOne("Mjm.LocalDocs.Infrastructure.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Mjm.LocalDocs.Infrastructure.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
